<div scroll="auto" class="col-xs-10 col-sm-10 col-md-10 col-lg-10  col-xs-offset-1 col-sm-offset-1 col-md-offset-1 col-lg-offset-1">
        <div class="row">
                <div class="col-md-6 col-md-offset-3" id="tituloo">Registrar Estudiante</div>
                <div class="col-md-6 col-md-offset-3"> 
                        <form id="form_agregar_producto" enctype="multipart/form-data" method="post" action=" <?php echo BASE_URL ?>alumno/guardar" >
                               
                               <div class="form-group">
                                        <label for="presentacion" class="titulo-form">Cedula del representante</label>
                                        <input type="text" class="form-control" id="cedula" name="cedula" placeholder="Cedula representante">
                                </div>

                                	<div class="datosrepresentante" id="datosrepresentante"> </div>
                              <div id="datosestudiante" hidden>

                              <div class="col-md-12" id="titulo">Datos del estudiante</div>
                                <div class="form-group">
                                        <label for="presentacion" class="titulo-form2">Nombres</label>
                                        <input type="text" class="form-control" id="nombres" name="nombres" placeholder="Nombres">
                                </div>

                                <div class="form-group">
                                        <label for="presentacion" class="titulo-form2">Apellidos</label>
                                        <input type="text" class="form-control" id="apellidos" name="apellidos" placeholder="Apellidos">
                                </div>

                                <div class="form-group">
                                        <label for="presentacion" class="titulo-form2">Grado</label>
                                        <input type="text" class="form-control" id="grado" name="grado" placeholder="Grado">
                                </div>

                                <div class="form-group">
                                        <label for="presentacion" class="titulo-form2">Talla Camisa</label>
                                        <input type="text" class="form-control" id="talla_camisa" name="talla_camisa" placeholder="Talla Camisa">
                                </div>

                                <div class="form-group">
                                        <label for="presentacion" class="titulo-form2">Talla Pantalon</label>
                                        <input type="text" class="form-control" id="talla_pantalon" name="talla_pantalon" placeholder="Talla Pantalon">
                                </div>
                                                              
                              
                                <div>  
                                        <center> 
                                                
                                                <button type="submit" class="btn btn-default">Guardar</button>
                                        </center>
                                </div>
                                 <div id="redireccion">  
                                        <center> 
                                                <a href="<?php echo BASE_URL ?>" >ir al inicio</a>
                                        </center>
                                </div>
                                </div>
                        </form>
                </div>
        </div>
</div>